# <center> NUMPY 2D ARRAY </CENTER>

In [4]:
import numpy as np

In [1]:
a=[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [2]:
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [5]:
a=np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [7]:
A.ndim

2

In [9]:
A.shape

(3, 3)

In [10]:
A=np.array([[11, 12], [21, 22], [31, 32]])
A

array([[11, 12],
       [21, 22],
       [31, 32]])

In [11]:
type(A)

numpy.ndarray

In [12]:
A.shape

(3, 2)

In [13]:
A.dtype

dtype('int32')

# Two Types of Multiplications:

In [16]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

In [17]:
C=A*B
C

array([[11,  0],
       [ 0, 22]])

In [18]:
np.multiply(A, B)

array([[11,  0],
       [ 0, 22]])

In [19]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(A, B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# Create  a 2D Array:

In [21]:
import numpy as np

In [22]:
a=[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [23]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [24]:
A.ndim

2

In [25]:
A.shape

(3, 3)

In [26]:
A.size

9

# Accessing Different Elements of a Numpy Array:

In [28]:
A[1, 2]

23

In [29]:
A[1][2]

23

In [30]:
A[0, 0]

11

In [31]:
A[0][0:2]

array([11, 12])

In [33]:
A[0:2, 2]

array([13, 23])

# Basic Operations:

In [34]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [35]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [36]:
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

In [37]:
Z=np.add(X, Y)
Z

array([[3, 1],
       [1, 3]])

In [38]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [39]:
z=Y*2
Z

array([[3, 1],
       [1, 3]])

In [40]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [41]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [42]:
Z=X*Y
Z

array([[2, 0],
       [0, 2]])

In [43]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [44]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [46]:
Z=np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [48]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [49]:
np.cos(Z)

array([[ 1.        , -0.41614684],
       [ 1.        , -0.41614684]])

In [50]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [51]:
C.T # Transpose of matrix

array([[1, 2, 3],
       [1, 2, 3]])

# Practice:

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a[0:2, 0]

array([1, 5])

In [54]:
A[0][0:2]

array([0, 1])